[droplets]

[droplets.sgp1-dro-legacy]
every = '2w'
retention = '4w'
oneshot = false

[volumes]

[volumes.sgp1-vol-website-db]
every = '1d'
retention = '10d'
oneshot = true

[volumes.sgp1-vol-grafana-db]
every = '2d'
retention = '2w'
oneshot = false
